# View vs. Copy für NumPy Arrays

- View: eine weitere Sicht aus einem Array: Änderungen in View beeinflüssen das Array selbst
- Copy: ein eigenständiges Objekt: Änderungen in Copy beeinflüssen das Array NICHT

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
cop = arr.copy()


In [2]:
arr

array([1, 2, 3, 4, 5])

In [3]:
cop

array([1, 2, 3, 4, 5])

In [4]:
cop[0] = 100

In [5]:
cop

array([100,   2,   3,   4,   5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
y = arr

In [8]:
y[-1] = 1000

In [9]:
y

array([   1,    2,    3,    4, 1000])

In [10]:
arr

array([   1,    2,    3,    4, 1000])

Numpy hat dazu zwei Methoden: `copy()` und `view()`

In [11]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

In [12]:
x is arr

False

In [13]:
y is arr

False

In [14]:
y[-1] = 50

In [15]:
y

array([ 1,  2,  3,  4, 50])

In [16]:
arr

array([ 1,  2,  3,  4, 50])

In [17]:
x

array([1, 2, 3, 4, 5])

In [18]:
x[0] = 100

In [19]:
x

array([100,   2,   3,   4,   5])

In [20]:
arr

array([ 1,  2,  3,  4, 50])

In [21]:
y

array([ 1,  2,  3,  4, 50])

In [22]:
z = arr # alias: zeigt auf dasselbe Objekt wie arr - ist auch eine View

### .base
Jedes Numpy-Array besitzt ein Attribut `.base`, welches verrät, ob das Array selbst das Original ist, oder nicht.

In [23]:
print(arr.base) # arr: original - nicht abhängig von einem anderen Array

None


In [24]:
print(x.base) # x: original - nicht abhängig von einem anderen Array

None


In [25]:
print(y.base) # y: ist eine View von [ 1  2  3  4 50]

[ 1  2  3  4 50]
