## Grundrechenarten
Importieren sie die Bibliothek `numpy` unter dem Namen `np`

In [1]:
import numpy as np

### Eindimensional
Gegeben sind zwei Arrays

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 7])

Bilden Sie die Summe, Differenz und das Produkt

In [6]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]


Was passiert, wenn Sie statt arr2, eine einzelne Zahl (num = 5) benutzen?

In [7]:
print(arr1+5)
print(arr1-5)
print(arr1*5)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]


### Zweidimensional
Diesmal ist eine Matrix gegeben:

In [8]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

Was passiert, wenn eine einzelne Zahl (num = 5) addieren?

In [9]:
print(arr_2d+5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Wie muss der Array aussehen, den man auf arr_2d addiert, damit das Ergebnis
```py
array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])
```       
ist? 


In [11]:
print(arr_2d+[[1],[2],[3]])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


Reshape
Oft ist es hilfreich, die Elemente eines Arrays anders anzuordnen. So kann man z.B. aus einem eindimensionalen Array der Länge 15, einen zweidimensionalen Array mit der Shape (3, 5) machen (drei Zeilen, fünf Spalten).

In [12]:
arr_1d = np.arange(15)
arr_2d = arr_1d.reshape((3, 5))

Machen Sie aus arr_2d einen Array mit

- fünf Zeilen und drei Spalten!

- fünfzehn Zeilen und einer Spalte

- einer Zeile und fünfzehn Spalten

- einen eindimensionalen Array

In [14]:
arr_2d = arr_2d.reshape((5, 3))
print(arr_2d)
print(arr_2d.reshape((15, 1)))
print(arr_2d.reshape((1, 15)))
print(arr_2d.reshape(15))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Slicing
### Eindimensional
Gegeben ist ein Array aus zwanzig Elementen:

In [15]:
arr = np.array(list("abcdefghiklmnopqrstuvwxyz"))

Lassen Sie sich die ersten 10 ausgeben (Die Syntax fürs Slicen ist wie bei Python-Listen)

In [16]:
arr[:10]

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k'], dtype='<U1')

### Zweidimensional
Diesmal ist ein zweidimensionaler Array mit vier Zeilen und fünf Spalten gegeben.

In [18]:
arr2d = arr[:20].reshape((4, 5))
arr2d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'k'],
       ['l', 'm', 'n', 'o', 'p'],
       ['q', 'r', 's', 't', 'u']], dtype='<U1')

Man kann auch in zwei (oder mehr) Dimensionen slicen. Beispiel:

```py
print(arr2d[:2, :2])
[['a' 'b']
 ['f' 'g']]
``` 
Benutzen Sie Slicing, um

a) die letzten drei Elemente der vorletzten Zeile auszugeben ("n", "o", "p")

In [19]:
arr2d[2:3,2:]

array([['n', 'o', 'p']], dtype='<U1')

b) den Ausschnitt [["g", "h"], ["m", "n"]] zu bekommen

In [20]:
arr2d[1:3,1:3]

array([['g', 'h'],
       ['m', 'n']], dtype='<U1')

#### Aufgabe (1)

Schreibe ein Python-Programm (**ohne NumPy**), welches folgende Temperaturen (Celsius) in Fahrenheit umrechnet!
```python
cel = [20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1]
```
$Fahrenheit =(Celsius \times \frac{9}{5})+32$

In [21]:
cel = [20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1]
fahrenheit = [i*9/5+32 for i in cel]
print(fahrenheit)

[68.18, 69.44, 71.42, 72.5, 72.86, 71.24000000000001, 70.34, 69.62, 68.18]


#### Aufgabe (2)

Schreibe ein Python-Programm (**mit NumPy**), welches folgende Temperaturen (Celsius) in Fahrenheit umrechnet!
```python
cel = [20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1]
```

In [22]:
cel_ar = np.array(cel)
cel_ar * 9 / 5 + 32

array([68.18, 69.44, 71.42, 72.5 , 72.86, 71.24, 70.34, 69.62, 68.18])

#### Aufgabe (3):
Wie sieht die Ausgabe des folgenden Codes aus und warum?
```python
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])
```

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])
print(a)

200
[  1 200   3   4   5]


#### Aufgabe (4)

  
Schreibe zwei Python-Programme, welche jeweils eine Liste, und einen NumPy-Array aus hunderttausend ganzen Zahlen generieren. Diese Zahlen können gern durch Zufall generiert werden.

Dann ermitlle die Größe der Liste und die Größe des Arrays.  
Das ``sys``-Modul aus der Pythons Standardbibliothek verfügt über eine Funktion ``getsizeof``, um die Größe von Objekten zu berechnen.
Wir müssen die Größe der Datenstruktur (z.B. der Liste) und die Größe der enthaltenen Elemente addieren !

Zufallszahlen können mit Hilfe der Bibliothek `random` erzeugt werden, z.B. mit der Funktion `randomint(a,b)`. Diese erzeugt eine zufällige Ganzahl zwischen `a` und `b`.
Numpy hat eine eigene `random` Funktionen, hier kann `np.random.randint(a, b, size=anzahl)` benutzt werden.

In [2]:
import sys
import random as r
a = np.random.randint(1, 100, size=100000)
print(a.dtype)
b = [r.randint(1, 100) for _ in range (100000)]
print(sys.getsizeof(a))
print(sys.getsizeof(b))
c = []
print(sys.getsizeof(c))

print(sys.getsizeof(b[1]))



int32
400112
800984
56
28


In [9]:
f=1
g=[1,[1,2]]
h=g
id(f), id(g[0]),id(g[1][0]), id(g), id(h) 

(140726595422648,
 140726595422648,
 140726595422648,
 1896079563392,
 1896079563392)

In [4]:
import sys
def deepgso(ob):
    size = sys.getsizeof(ob)
    if isinstance(ob, (list,tuple,set)):
        for element in ob:
            size+=deepgso(element)
    if isinstance(ob, dict):
        for k,v in ob.items():
            size+=deepgso(k)
            size+=deepgso(v)
    return size
# print(deepgso(a))
print(deepgso(b))
print(deepgso(c))

400112
3600984
56


In [5]:

3600984-100000*28


800984

#### Aufgabe (5)

Erweitere die Programme aus Aufgabe (4), sodass die Zeitdauer bei Erstellung von Liste und Array separat berechnet werden können.  
Das Modul ``time`` aus der Pythons Standardbibliothek verfügt über eine Funktion ``time``, welche den aktuellen Zeitpunkt als eine Kommazahl zurückliefert.  

Vergleiche dann die Zeitdauer von zwei Programmen.

In [34]:
import numpy as np
import time
dt1 = time.time()
a = np.random.randint(0, 15, size=100000)
dt2 = time.time()
print("Array: ", (dt2-dt1)*1000)
dt3 = time.time()
b = [r.randint(0, 15) for _ in range (100000)]
dt4 = time.time()
print("List: ", (dt4-dt3)*1000)

Array:  1.0771751403808594
List:  52.11305618286133


In [35]:
# Jupyter-Magic
print("Für List")
%timeit random_list = [r.randint(0, 15) for _ in range (100000)]
print("für array")
%timeit random_array = np.random.randint(0, 15, size=100000)

Für List
47.7 ms ± 915 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
für array
498 μs ± 7.99 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [37]:
%%timeit -r 5 -n 3 # -r: Anzahl der Wierderholung, -n: Anzahl der Schleifen pro Messung
liste = []
for _ in range(100000):
    liste.append(r.randint(0, 15))

51.3 ms ± 7.78 ms per loop (mean ± std. dev. of 5 runs, 3 loops each)


In [38]:
%%timeit -r 5 -n 3
arr = np.array([])
for _ in range(100000):
    arr = np.append(arr, r.randint(0, 15))

1.85 s ± 118 ms per loop (mean ± std. dev. of 5 runs, 3 loops each)
