In [3]:
import numpy as np

Convert a 1D array to a 2D array with 2 rows
- Input:
- np.arange(10)
- array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
- Desired Output:
- array([[0, 1, 2, 3, 4],
 -    [5, 6, 7, 8, 9]])

In [2]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2 = np.array(arr1, ndmin=2)
arr2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
arr1.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Replace all odd numbers in arr with -1 without changing arr
- Input:
- arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
- Output:
- array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
- arr
- array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [10]:
arr_copy = arr.copy()
cond = lambda x: x%2 != 0

# new_arr = np.where(arr_copy % 2 != 0, -1, arr_copy)
arr_copy[cond(arr)]= -1
arr_copy

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
cond=lambda x: x%2 !=0
cond(arr)

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

Get the common items between a and b
- Input:
- a = np.array([1,2,3,2,3,4,3,4,5,6])
- b = np.array([7,2,10,2,7,4,9,4,9,8])
- Desired Output:
- array([2, 4])

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

Stack arrays a and b vertically (concatenate recherchieren)
- Input
- a = np.arange(10).reshape(2,-1)
- b = np.repeat(1, 10).reshape(2,-1)
- Desired Output:
- #> array([[0, 1, 2, 3, 4],
- #> [5, 6, 7, 8, 9],
- #> [1, 1, 1, 1, 1],
- #> [1, 1, 1, 1, 1]])

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
a_b= np.concatenate((a, b), axis=0)
a_b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally.
- Input
- a = np.arange(10).reshape(2,-1)
- b = np.repeat(1, 10).reshape(2,-1)
- Desired Output:
- #> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
- #> [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
a_b= np.concatenate((a, b), axis=1)
a_b

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])