# Numpy Teil 2

In [1]:
import numpy as np

### Zufallszahlen erzeugen

`seed()` 
setzt den Startwert des Zufallszahlengenerators.

In [2]:
np.random.seed(42)

`random()` zieht Zufallszahlen aus einer gleichverteilten Verteilung im Intervall [0, 1). Mit `size` kann die Anzahl der Werte angegeben werden oder die Dimension:

In [3]:
print(np.random.random())
print(np.random.random(size=5))
print(np.random.random(size=(3,3)))

0.3745401188473625
[0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


`randint()`
zieht zufällige Ganzzahlen aus einem gegebenen Intervall

In [12]:
np.random.randint(1, 10, 5)  # 5 Ganzzahlen zwischen 1 und 10

array([9, 1, 9, 7, 9], dtype=int32)

In [14]:
np.random.randint(1, 100, size=(3,3)) # Mit ANgabe der Array Dimensionen

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75]], dtype=int32)

`choice()` zieht zufällig Werte aus einer gegebenen Liste oder Array.

In [15]:
np.random.choice([1, 2, 3, 4, 5, 6, 7, 8], size=3, replace=False) # 3 Werte aus der Liste, ohne Wiederholung wenn replace=False

array([7, 6, 1])

`permutation()` liefert eine zufällige Permutation einer Sequenz

In [16]:
np.random.permutation([1, 2, 3, 4])

array([1, 3, 2, 4])

In [1]:
import numpy as np
rng = np.random.default_rng()
x = np.arange(0, 15).reshape(3, 5)
print(x)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])
# rng.permutation(x, axis=1) 
# array([[ 1,  3,  2,  0,  4],  # random
#        [ 6,  8,  7,  5,  9],
#        [11, 13, 12, 10, 14]])
rng.permutation(x) 
# array([[10, 11, 12, 13, 14],
#        [ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

`shuffle()`
vermischt eine Sequenz und ändert ursprüngliche Array verändert

In [17]:
arr = [1, 2, 3, 4]
np.random.shuffle(arr)
arr

[4, 3, 1, 2]

`uniform()`
zieht Stichproben aus einem Intervall

In [18]:
np.random.uniform(0, 100, 10)  # 10 Stichproben zwischen 0 und 1

array([30.4242243 , 52.47564316, 43.19450186, 29.12291402, 61.18528947,
       13.94938607, 29.21446485, 36.63618433, 45.60699842, 78.51759614])

`standard_normal()`
zieht Stichproben aus einer Normalverteilung mit dem Mittelwert 0 und der Standardabweichung 1<br>
alte Methode heisst `randn()`

In [19]:
np.random.standard_normal(10)  # 10 Stichproben

array([ 0.0675282 , -1.42474819, -0.54438272,  0.11092259, -1.15099358,
        0.37569802, -0.60063869, -0.29169375, -0.60170661,  1.85227818])

`binomial()`
zieht Stichproben aus einer Binomialverteilung.

In [20]:
np.random.binomial(n=10, p=0.5, size=10)  # 10 Stichproben aus einer Binomialverteilung

array([3, 5, 2, 7, 4, 6, 4, 5, 5, 4], dtype=int32)

`normal()`
zieht Stichproben aus einer Normalverteilung (gausssche Verteilung)

In [21]:
np.random.normal(loc=0, scale=1, size=10)  # Mittelwert=0, Standardabweichung=1

array([ 0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
       -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016])