# NumPy Übung - Aufgabe

Jetzt wo wir schon einiges über NumPy gelernt haben können wir unser Wissen überprüfen. Wir starten dazu mit einigen einfachen Aufgaben und steigern uns zu komplizierteren Fragestellungen.

**Importiere NumPy als np**

In [1]:
import numpy as np

**Erstelle ein Array von 10 Nullen**

In [41]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Erstelle ein Array von 10 Einsen**

In [3]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Erstelle ein Array von 10 Fünfen**

In [43]:
arr2 = np.full((10,), 5)
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

**Erstelle ein Array der Zahlen von 10 bis 50**

In [8]:
arr3 = np.arange(10, 51)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Erstelle ein Array aller gerader Zahlen zwischen 10 und 50**

In [9]:
arr4 = np.arange(10, 51, 2)
arr4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Erstelle eine 3x3 Matrix, die die Zahlen von 0 bis 8 beinhaltet**

In [11]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Erstelle eine 3x3 Einheitsmatrix**

In [12]:
arr6 = np.eye(3, 3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Nutze NumPy, um eine Zufallszahl zwischen 0 und 1 zu erstellen**

In [13]:
np.random.rand()

0.7256226938091603

**Nutze NumPy, um ein Array von 25 Zufallszahlen zu erstellen**

In [22]:
np.random.seed(42)

In [25]:
arr8 = np.random.rand(25)
#np.random.randint(1,100,25)
arr8

array([0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
       0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033,
       0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
       0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694,
       0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685734])

**Erstelle die folgende Matrix:**
```py
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [45]:
arr7 = np.linspace(0.01, 1, num=100).reshape(10,10)
arr7

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Erstelle ein Array aus 20 gleichmäßig verteilten Punkten zwischen 0 und 1**

In [44]:
arr9 = np.linspace(0, 1, num=20)
# arr9 = np.linspace(0, 1, 20)
arr9

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## NumPy Indexing und Selection

Erzeuge folgende Matrix M:
```py
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [28]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
arr10 = np.arange(1, 26).reshape((5,5))
arr10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Benutze Slicing um aus M folgende Matrix auszuwählen:
```py
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [29]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
arr10[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Wähle aus M folgenden Wert aus: 20

In [31]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
print(arr10[3,4])  #arr[-2,-1]

20


Benutze Slicing um aus M folgende Matrix auszuwählen:
```py
array([[ 2],
       [ 7],
       [12]])
```

In [47]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
arr10[:3, 1:2]

array([[16, 17, 18, 19, 20],
       [ 6,  7,  8,  9, 10]])

Benutze Slicing um aus M folgende Matrix auszuwählen:
```py 
array([21, 22, 23, 24, 25])
````

In [39]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
arr10[4, :] # [-1,:]

array([21, 22, 23, 24, 25])

Benutze Slicing um aus M folgende Matrix auszuwählen:
```py
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [49]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
arr10[[3, 4]]
# arr10[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
arr10[[3, 4]][:, [1, 2, 3]]

array([[17, 18, 19],
       [22, 23, 24]])