# Numpy Teil 3

## `ufunc` - schnelle elementweise Array-Funktionen
In NumPy steht der Begriff ufunc für universal function (universelle Funktion). Diese Funktionen sind spezielle Funktionen, die auf NumPy-Arrays angewendet werden können, um elementweise Operationen durchzuführen. Ufuncs sind sehr effizient und ermöglichen es uns, Berechnungen in einer vektorisierte Form durchzuführen, was oft schneller ist als das Verwenden von Schleifen in Python.<br>
[Universelle Array Funktionen](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [25]:
import numpy as np

### Einfache elementweise Transformationen - _unäre_ ufuncs

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`sqrt()` Wurzel berechnen

In [27]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

`exp()` Exponentialfunktion

In [28]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### Funktionen für zwei Arrays - _binäre_ ufuncs

In [29]:
x = np.random.standard_normal(8)
x

array([-0.57799856, -0.51155065,  1.60672168, -0.42605929, -0.00706472,
       -0.21886081, -1.02100363, -1.6541453 ])

In [30]:
y = np.random.standard_normal(8)
y

array([ 1.78783892, -0.32951794, -0.26294883, -3.64858647,  0.35828413,
       -1.63048333, -0.42413149, -0.11584165])

`minimum()` und `maximum()`

In [31]:
np.minimum(x, y)

array([-0.57799856, -0.51155065, -0.26294883, -3.64858647, -0.00706472,
       -1.63048333, -1.02100363, -1.6541453 ])

In [32]:
np.maximum(x, y)

array([ 1.78783892, -0.32951794,  1.60672168, -0.42605929,  0.35828413,
       -0.21886081, -0.42413149, -0.11584165])

### `ufuncs` mit mehreren Rückgabewerten
`modf()`
gibt die gebrochenen und ganzzahligen Anteile eines Arrays als separate Arrays zurück.

In [33]:
arr = np.random.standard_normal(7) * 5
arr

array([-2.20658668, -2.12860249, -1.49273915,  4.36013423,  3.61825955,
        9.20203542, -2.76619699])

In [34]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.20658668, -0.12860249, -0.49273915,  0.36013423,  0.61825955,
        0.20203542, -0.76619699])

In [35]:
whole_part

array([-2., -2., -1.,  4.,  3.,  9., -2.])

### `out` Argument
`ufuncs` akzeptieren ein optionales out-Argument, das ihnen erlaubt, ihre Ergebnisse einem bestehenden Array zuzuweisen, statt ein neues zu erstellen:

In [36]:
out = np.zeros_like(arr) # siehe unten
np.add(arr, 1, out=out)
out

array([-1.20658668, -1.12860249, -0.49273915,  5.36013423,  4.61825955,
       10.20203542, -1.76619699])

### Auswahl unärer Funktionen
<pre><b>
Funktion                                Beschreibung</b>

abs, fabs                               Berechnet elementweise den absoluten Wert für Integer-, Gleitkomma- oder komplexe Werte.

sqrt                                    Berechnet für jedes Element die Quadratwurzel (äquivalent zu arr ** 0.5).

square                                  Berechnet das Quadrat jedes Elements (äquivalent zu arr ** 2).

exp                                     Berechnet den Exponenten ex jedes Elements.

log, log10, log2, log1p                 Natürlicher Logarithmus (Basis e), log Basis 10, log Basis 2 bzw. log(1 + x).

sign                                    Berechnet das Vorzeichen jedes Elements: 1 (positiv), 0 (null) oder –1 (negativ).

ceil                                    Rundet jedes Element auf die kleinste Integer-Zahl auf, die größer oder gleich diesem Element ist.

floor                                   Rundet jedes Element auf die größte Integer-Zahl ab, die kleiner oder gleich diesem Element ist.

rint                                    Rundet Elemente auf die nächstgelegene Integer-Zahl, wobei der dtype beibehalten wird.

modf                                    Gibt die gebrochenen und ganzzahligen Anteile eines Arrays als separate Arrays zurück.

isnan                                   Gibt ein boolesches Array zurück, das angibt, ob die einzelnen Werte NaN (Not a Number, keine Zahl) sind.

isfinite, isinf                         Gibt ein boolesches Array zurück, das angibt, ob die einzelnen Werte endlich (nicht-inf, nicht-NaN) bzw. unendlich sind.

logical_not                             Berechnet elementweise den Wahrheitswert von not x (äquivalent zu ~arr).

cos, cosh, sin, sinh, tan, tanh         Reguläre trigonometrische und Hyperbelfunktionen.

arccos, arccosh, arcsin, arcsinh, 
arctan, arctanh                         Inverse trigonometrische Funktionen.
</pre>

### Auswahl binärer Funktionen
<pre><b>
Funktion                                Beschreibung</b>
add                                     Addiert korrespondierende Elemente in Arrays.

subtract                                Subtrahiert die Elemente im zweiten Array vom ersten Array.

multiply                                Multipliziert die Array-Elemente miteinander.

divide, floor_divide                    Dividieren oder Floor-Dividieren (Abschneiden des Rests).

power                                   Potenziert Elemente im ersten Array entsprechend dem Exponenten im zweiten Array.

maximum, fmax                           Elementweises Maximum; fmax ignoriert NaN.

minimum, fmin                           Elementweises Minimum; fmin ignoriert NaN.

mod                                     Elementweiser Modulus (Rest der Division).

copysign                                Kopiert die Vorzeichen der Werte im zweiten Argument auf die Werte im ersten Argument.

logical_and                             Berechnet elementweise die Wahrheitswerte von AND (&).

logical_or                              Berechnet elementweise die Wahrheitswerte von OR (|).

logical_xor                             Berechnet elementweise die Wahrheitswerte von XOR (^).

greater, greater_equal, less, 
less_equal, equal, not_equal            Führt elementweise Vergleiche durch, die ein boolesches Array ergeben (äquivalent zu den Infix-Operatoren >, >=, <, <=, ==, !=).
</pre>

## Erzeung von Arrays mit `like`
In NumPy gibt es mehrere Funktionen, die das Suffix like verwenden, um neue Arrays zu erstellen, die ähnliche Eigenschaften wie ein gegebenes Array aufweisen.

In [37]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`zeros_like()`<br>
Erstellt ein Array der gleichen Form und des gleichen Datentyps wie a, gefüllt mit Nullen.

In [38]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`ones_like()`<br>
Erstellt ein Array der gleichen Form und des gleichen Datentyps wie a, gefüllt mit Einsen

In [39]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

`empty_like()`<br>
Erstellt ein Array der gleichen Form und des gleichen Datentyps wie a, ohne die Werte zu initialisieren (die Werte sind unbestimmt).

In [40]:
np.empty_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`full_like()`
Erstellt ein Array der gleichen Form und des gleichen Datentyps wie a, gefüllt mit dem angegebenen Wert fill_value.

In [41]:
np.full_like(arr, 7) #(füllt das Array mit dem Wert 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Dateiein- und ausgabe
NumPy ist in der Lage, Daten in einigen Text- und Binärformaten auf der Festplatte zu speichern und von ihr zu laden. Arrays werden standardmäßig in einem unkomprimierten rohen Binärformat mit der Dateierweiterung .npy gespeichert. Sollte der Dateipfad noch nicht auf .npy enden, wird die Erweiterung angehängt.

In [42]:
arr = np.arange(10)
np.save("my_array", arr)

Laden des Arrays:

In [43]:
np.load("my_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Speichern mehrerer Arrays via Keyword Argument in einem unkomprimierten Archiv, Endung `npz`

In [44]:
np.savez("my_archive.npz", a=arr, b=arr)

Laden eines `npz`, auf die Arrays kann mit einer dict Struktur zugegriffen werden:

In [46]:
my_arrs = np.load("my_archive.npz")
my_arrs['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Speichern mit Komprimierung:

In [49]:
np.savez_compressed("my_arrs_compressed.npz", a=arr, b=arr)

In [50]:
my_arrs = np.load("my_arrs_compressed.npz")
my_arrs['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])