In [1]:
import numpy as np

### Aufgabe 0 
Gegeben ist folgender Array: np.array( ["Rot", "Grün", "Rot", "Blau", "Rot", "Grün", "rot"]) Ermitteln sie die einzigartigen Werte des Arrays mit einer dafür geeigneten numpy Funktion.

In [2]:
color_ar = np.array( ["Rot", "Grün", "Rot", "Blau", "Rot", "Grün", "rot"])
np.unique(color_ar)

array(['Blau', 'Grün', 'Rot', 'rot'], dtype='<U4')

### Aufgabe 0.5
  Gegeben sind folgende Arrays: array_a = np.array([1, 2, 3, 4, 5]) array_b = np.array([3, 4, 5, 6, 7]) Ermitteln Sie mit np.isin() welche Werte von array_a in array_b vorhanden sind. Benutzen Sie einen boolschen Index um einen Array zu erzeugen der die gemeinsamen Werte enthält.


In [3]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([3, 4, 5, 6, 7])
np.isin(array_a, array_b)

array([False, False,  True,  True,  True])

### Aufgabe 0.75
 Führen Sie die folgenden Mengenoperationen an den Arrays aus 0.5 durch: 1. Schnittmenge 2. Vereinigungsmenge 3. Differenzmenge 

In [4]:
# Schnittmenge

np.intersect1d(array_a, array_b)

array([3, 4, 5])

In [5]:
# Vereinigungsmenge
np.union1d(array_a, array_b)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# Differenzmenge 
np.setdiff1d(array_a, array_b)

array([1, 2])

In [7]:
np.setxor1d(array_a, array_b)

array([1, 2, 6, 7])

### Aufgabe 1 
Erstellen Sie ein 2D-Array mit zufälligen Werten und sortieren Sie es einmal nach Zeilen und einmal nach Spalten. Verwenden Sie dafür np.sort() mit Angabe des entsprechenden Werts für axis . 

In [16]:
arr_s = np.random.standard_normal((5,4))
arr_s

array([[ 1.25052118,  1.66350608, -1.16059556, -0.37016564],
       [-0.26851991,  0.08750502, -0.52112441, -0.21082812],
       [-0.19491863, -0.05195392,  0.57176942, -0.8541492 ],
       [ 0.91603256,  0.78218242, -2.24002973,  1.31637557],
       [-1.19221337, -0.7335166 ,  0.43028811,  0.43925519]])

In [17]:
arr_s1 = arr_s.copy()
arr_s1.sort(axis=1)
arr_s1

array([[-1.16059556, -0.37016564,  1.25052118,  1.66350608],
       [-0.52112441, -0.26851991, -0.21082812,  0.08750502],
       [-0.8541492 , -0.19491863, -0.05195392,  0.57176942],
       [-2.24002973,  0.78218242,  0.91603256,  1.31637557],
       [-1.19221337, -0.7335166 ,  0.43028811,  0.43925519]])

In [18]:
arr_s0 = arr_s.copy()
arr_s0.sort(axis=0)
arr_s0

array([[-1.19221337, -0.7335166 , -2.24002973, -0.8541492 ],
       [-0.26851991, -0.05195392, -1.16059556, -0.37016564],
       [-0.19491863,  0.08750502, -0.52112441, -0.21082812],
       [ 0.91603256,  0.78218242,  0.43028811,  0.43925519],
       [ 1.25052118,  1.66350608,  0.57176942,  1.31637557]])

### Aufgabe 2
 Gegeben ist folgender Array: np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) Benutzen Sie np.sum() mit dem Argument axis um die Summe aller Werte für jede Zeile des Arrays zu berechnen. Das Ergebnis sollte ein 1D-Array sein, das die Summen der jeweiligen Zeilen enthält. die Summe aller Werte für jede Spalte des Arrays zu berechnen. Das Ergebnis sollte ebenfalls ein 1D-Array sein, das die Summen der jeweiligen Spalten enthält. 

In [23]:
arr_f_s = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_s_z = np.sum(arr_f_s, axis=1)
arr_f_s, arr_s_z

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([10, 26, 42]))

In [24]:
arr_s_s = np.sum(arr_f_s, axis=0)
arr_s_s

array([15, 18, 21, 24])

### Aufgabe 3
 Gegeben ist ein 1D-Array mit Integer-Zahlen, der einige Nullen enthält. np.array([10, 0, 5, 20, 0, 25]) Verwenden Sie np.where() , um ein neues Array zu erstellen, in dem die Werte von 100 durch die Elemente des ursprünglichen Arrays geteilt werden. Wenn ein Element des Arrays den Wert 0 hat, soll an dieser Stelle np.nan (Not a Number) eingetragen werden. 

In [43]:
arr_where = np.array([10, 0, 5, 20, 0, 25])
np.where(arr_where != 0, 100/arr_where, np.nan)

C:\Users\OlhaIshchenko\AppData\Local\Temp\ipykernel_8232\2977442286.py:2: RuntimeWarning: divide by zero encountered in divide
  np.where(arr_where != 0, 100/arr_where, np.nan)


array([10., nan, 20.,  5., nan,  4.])

In [49]:
100 / arr_where

C:\Users\OlhaIshchenko\AppData\Local\Temp\ipykernel_8232\1116973131.py:1: RuntimeWarning: divide by zero encountered in divide
  100 / arr_where


array([10., inf, 20.,  5., inf,  4.])

### 3.1:
 Erstellung des Filters Erstellen Sie einen Filter (in diesem Fall einen booleschen Index), der angibt, welche Elemente im ursprünglichen Array ungleich 0 sind. 

In [44]:
arr_cond = np.where(arr_where != 0, True, False)
# filter = original_ar !=0
arr_cond

array([ True, False,  True,  True, False,  True])

### 3.2:
  Erstellung des Ergebnis-Arrays Verwenden Sie den erstellten Filter, um ein neues Array zu erstellen, in dem die Werte von 100 durch die Elemente des ursprünglichen Arrays geteilt werden. An den Stellen, an denen der Filter False ist (also die Elemente 0), sollte np.nan eingetragen werden. 

In [45]:
arr_res = np.where(arr_cond, 100/arr_where, np.nan)
arr_res

C:\Users\OlhaIshchenko\AppData\Local\Temp\ipykernel_8232\194720381.py:1: RuntimeWarning: divide by zero encountered in divide
  arr_res = np.where(arr_cond, 100/arr_where, np.nan)


array([10., nan, 20.,  5., nan,  4.])

### 3.3 
 np.any() und np.all() Benutzen sie eine der beiden Funktionen um zu testen ob im erstellten Array mindestens ein np.nan eingetragen ist. Benutzen Sie eine der Funktionen um zu testen ob im Array kein np.nan vorkommt. 

In [46]:
arr_res.any()

np.True_

In [47]:
arr_res.all()

np.True_

### 3.4: 
 np.nan zählen Ermitteln sie die Anzahl der np.nan im Ergebnis. Sie können dazu die Funktion sum() in Verbindung mit dem boolschen Index benutzen.

In [48]:
arr_nan_count = np.where(arr_cond , 0 , 1)
arr_nan_count.sum()

np.int64(2)

In [55]:
np.sum(~arr_cond)

np.int64(2)

In [51]:
nan_count = np.sum(np.isnan(arr_res))
nan_count

np.int64(2)